version: '3'

services:
  authservice:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  
  db:
    image: postgres:14.13-alpine3.20
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: microservicos
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
